unittest:
  image: ghcr.io/puppeteer/puppeteer:latest
  before_script:
#    - git clone https://gitlab.muze.nl/muze/simply-test-store.git /tmp/simply-test-store
#    - ( php -S 0.0.0.0:80  & )
#    - ( cd /tmp/simply-test-store ; bash server.sh )
    - npm install node-qunit-puppeteer
  script:
     - ./node_modules/.bin/node-qunit-puppeteer ./tests/data-display/ci.html 60000 "--no-sandbox --allow-file-access-from-files"
     - ./node_modules/.bin/node-qunit-puppeteer ./tests/data-edit/ci.html 60000 "--no-sandbox --allow-file-access-from-files"
     - ./node_modules/.bin/node-qunit-puppeteer ./tests/triplebinding/ci.html 60000 "--no-sandbox --allow-file-access-from-files"
  tags:
    - docker
  stage: test

syntaxtest:
  image: muze/phantomjs:v2latest
  before_script:
    - npm -g install jshint
    - npm -g install csslint
  script:
    - echo '{"esversion":6}' > .jshintrc
    - jshint --config .jshintrc $(find js simply  -name \*.js | grep -v -E '^(simply/slip.js|simply/scripts.js)$')
    - csslint .
  tags:
    - docker
  stage: test

canary:
  stage: deploy
  environment: canary
  image: muze/deployer:latest
  when: on_success
  only:
    - master@muze/simple-edit
    - /^master-[0-9]+$/@muze/simple-edit
  tags:
    - dc
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - composer --working-dir=.deploy/ install --no-scripts
    - 'NEXT=$(git for-each-ref  --format="%(refname:short)" **/origin/master-* | sort | tr -d -c "[:digit:]\n" | sort -nr | head -n1)'
    - 'NEXT=$((${NEXT:=-1}+1))'
    - 'if [ "${CI_COMMIT_REF_NAME}" == "master" ] ; then export MAJOR=${NEXT} ; else export MAJOR=$(echo "${CI_COMMIT_REF_NAME}" | tr -d -c "[:digit:]" ) ; fi '
  script:
    - dep --file=.deploy/deploy.php -vv deploy canary

deploy-cdn:
  stage: deploy
  environment: cdn
  image: muze/deployer:latest
  when: on_success
  only:
    - tags@muze/simple-edit
  tags:
    - dc
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - composer --working-dir=.deploy/ install --no-scripts
  script:
    - dep --file=.deploy/deploy.php -vv release cdn
